### ISSUE TITLE
Librosa can't be imported on new environnments

### ISSUE THREAD

**Issue by cedricviaccoz** [DCMLab/wavescapes#8]
After creating a new virtual environnment and having installed the module `wavescapes` on it, the following error happens:

```Python 3.7.7 (default, Apr 26 2020, 16:58:14) 
[Clang 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from wavescapes import *
import matplTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cedricviaccoz/pytest/lib/python3.7/site-packages/wavescapes/__init__.py", line 1, in <module>
    from wavescapes.wavescapes import Wavescape, produce_pitch_class_matrix_from_filename, apply_dft_to_pitch_class_matrix, complex_utm_to_ws_utm, legend_decomposition, generate_all_wavescapes
  File "/Users/cedricviaccoz/pytest/lib/python3.7/site-packages/wavescapes/wavescapes.py", line 5, in <module>
    from librosa.feature import chroma_stft
  File "/Users/cedricviaccoz/pytest/lib/python3.7/site-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/Users/cedricviaccoz/pytest/lib/python3.7/site-packages/librosa/core/__init__.py", line 125, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "/Users/cedricviaccoz/pytest/lib/python3.7/site-packages/librosa/core/time_frequency.py", line 11, in <module>
    from ..util.exceptions import ParameterError
  File "/Users/cedricviaccoz/pytest/lib/python3.7/site-packages/librosa/util/__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/Users/cedricviaccoz/pytest/lib/python3.7/site-packages/librosa/util/utils.py", line 15, in <module>
    from .decorators import deprecated
  File "/Users/cedricviaccoz/pytest/lib/python3.7/site-packages/librosa/util/decorators.py", line 9, in <module>
    from numba.decorators import jit as optional_jit
ModuleNotFoundError: No module named 'numba.decorators'
>>> 
``` 

This is a known problem by librosa's developpers (see [this issue](https://github.com/librosa/librosa/issues/1160)) and can be solved by forcing the installation of an older version of the module `numba`(version 0.48). However a new release of librosa might come in a few week to resolve this problem with the most recent version of numba (version 0.50).

Dependencies of the wavescapes library can be set to constraint the use of a previous version of numba, however I'm afraid people having the latest version of numba beforehand might still encounter this problem. Librosa is only useful to produce chromagrams from audio file, and considering wavescapes on audio files do not yield goode results, I would prefer to remove this feature for the first release and delay it later, once librosa solve this issue and when the audio feature for wavescapes is less experimental (see issue #1)

**Comment by fabianmoss** [comment]
I agree with your suggestion to not include this feature in the initial release. But let's keep watching librosa's development and add it as soon as it is fixed on their side.

**Comment by cedricviaccoz** [comment]
So librosa 8.0 has just been released, and although I haven't tested it, this [PR](https://github.com/librosa/librosa/pull/1107) meant for 8.0 has fixed the issue with numba, meaning it should now be working properly with the wavescapes. 

However, I would still like to wait a bit that I improve the audio feature overall before adding back librosa dependencies on wavescapes plotting, as in its current state the audio feature is really poor in terms of visual quality. Furthermore considering the target demographic of this library, I don't think this feature will be lacking in the next release considering both MIDI and MusicXML will be supported.

**Comment by cedricviaccoz** [comment]
Librosa has been dropped in favor of madmom for chromagram production in the first release, hence making the issue irrelevant.
